spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

openai:
  api:
    key: ${OPENAI_API_KEY}

# SpringDoc configurations
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html